### PR TITLE
Tests : Use slant instead of doh to use only fonts-contrib

### PR DESCRIPTION
**Pull request by LyesSaadi**
Hi!
This is to fix tests in the Fedora package which just got approved, btw :tada:!

### CODE REVIEW

**Comment by peterbrittain** [comment]
All looks good to me!  Thanks for packaging up the project @LyesSaadi.

On a related note, did you ever resurrect the associated asciimatics package?

**Comment by LyesSaadi** [comment]
> On a related note, did you ever resurrect the associated asciimatics package?
 
Yes ! I'm going to ! I don't think I'll package `present` though, since it has been dead for 3 years now.

**Comment by peterbrittain** [comment]
> Yes ! I'm going to ! I don't think I'll package `present` though (the original reason I packaged pyfiglet), since it has been dead for 3 years now.

Thanks!  And that makes sense...  I like `present`, but with no active maintainer, I agree that it's not worth the effort.

**Comment by pwaller** [comment]
Great news. Also happy to see things progressed in my absence, thanks for that. I take it this doesn't warrant a new release for now, but if it does please feel free to create one via the github UI, which should also put the artefacts on pypi and so forth.

https://github.com/pwaller/pyfiglet/compare/v1.0.2..main

Also please @ ping me if I'm needed and feel free to repeat with a frequency of weekly if I don't respond quickly in case it drops out of my inbox.

**Pull request merged**
