### PR TITLE
Fix for #89 - clarify font licensing

### PR DESCRIPTION
**Pull request by peterbrittain**
Hopefully this is everything we agreed...

- Fonts now separated out into 2 directories
- Makefule updated to make it easy to build minimal or full font definitions
- Docs updated to say what's happened.

I didn't go for the BDF files in the end as I wasn't so sure about the legality, while the other explicit license text was much more reassuring.

Are we good to go?

### CODE REVIEW

**Comment by peterbrittain** [comment]
Didn't spot the tests...  They should work now.

**Comment by peterbrittain** [comment]
So...  I think you're saying I should insert the original BSD license in the standard figlet font files (and check again what flf files are missing).  Right?  If so, I can probably do that over the weekend...

BTW, I don't think we need the flc files as these are just character mappings for non-standard code pages (which pyfiglet has been working with happily for many a year).

**Comment by LyesSaadi** [comment]
Just dropping the License file somewhere is enough. Putting it in the header could be practical for consistency, but is not mandatory. It's just that it is a requirement for BSD.

**Comment by peterbrittain** [comment]
OK  - I've now updated each font file with the original BSD license and tested they still work on a new build.  

I also took the latest files from figlet just to make sure that we weren't accidentally pulling in dodgy versions from elsewhere.  This added a new character to the standard font (in case you spotted that!).

I think that's it!

**Comment by peterbrittain** [comment]
@LyesSaadi - just checking...  Are you happy with the license update?

**Comment by LyesSaadi** [comment]
Oops, sorry, I forgot to answer. And to answer, yes, I'm happy with all that :tada:! That was awesome work from you!

I will also try & re-open the discussion with Fedora Legal later this week!

**Comment by peterbrittain** [comment]
@pwaller - looks like we're good to go...  Are you happy with the new changes?

**Comment by pwaller** [comment]
Thanks both.

@LyesSaadi 
> I will also try & re-open the discussion with Fedora Legal later this week!

Can I check what open questions remain here? I take it we're good to go?

**Comment by LyesSaadi** [comment]
> Can I check what open questions remain here? I take it we're good to go?

Yes, we're good to go!

I'm only referring to the remaining fonts (those in the `contrib/` directory) as John Cowan suggested that FIGlet fonts may be considered as insufficiently creative to be copyright-able. The issue is that there is no clear ruling toward FIGlet fonts specifically. So, I will open a discussion with Fedora Legal to ask for their view on that, and we'll maybe be able to get all the remaining fonts (and potentially all existing FIGlet fonts) into Fedora (and other Linux distributions).

This was a question which was actually already opened in the past with the figlet package (~2006-2012), but I couldn't find any conclusion from Fedora Legal toward the question, and the figlet package ended up being exclusively distributed with Open-Source fonts. But it could also be that the discussion was just lost, as Fedora changed its means of internal communication since.

**Pull request merged**
