### PR TITLE
Added: Double-Blocky Font

### PR DESCRIPTION
**Pull request by CatPieLeaf**
```
 ▄▄█ ▄▀▄ █░█ █▄▄ █░ ██▀  ██▄ █░░ █▀█ █▀▀ █░█ █▄█ █
 █▄█ ▀▄▀ ▀▄█ █▄█ █▄ █▄▄  █▄█ █▄▄ █▄█ █▄▄ █▀▄ ░█░ ▄
                                     by CatPieLeaf
```
_A font that uses only TWO rows of unicode blocks!_

This PR Adds the **Double-Blocky Font!** Based in the font _"Blocks in two lines"_ from https://texteditor.com/multiline-text-art/ and the second font from https://fsymbols.com/generators/tarty/. Double blocky contains much more characters than both, some modified and original ones (like `M`, `W`, `I`, `l`, `z`), uppercase/lowercase differentiation and all punctuation signs.
it was made by using https://textpaint.com and https://patorjk.com/figlet-editor/#/edit

## Preview:

> Lowercase:
```
 ▄▀▄ █▄▄ ▄▀▀ ▄▄█ ██▀ █▀ ▄▀░ ▀ ░░▀ █░▄ █░ ▄▀▄▀▄ ▄▀█ ▄▀▄ █▀▄ █▀█ █▀▄ █▀ ▄█▄ █░█
 █▀█ █▄█ ▀▄▄ █▄█ █▄▄ █▀ ▀▄█ █ ▀▄█ █▀▄ █▄ █░▀░█ █░█ ▀▄▀ █▀░ ▀▀█ █▀▄ ▄█ ░█▄ ▀▄█
abcdefghijklmnopqrstu

 █░█ █░▄░█ █░█ ▀▄▀ ▀█
 ▀▄▀ ▀▄▀▄▀ ▄▀▄ ░█░ █▄
vwxyz
```

> Uppercase:
```
 ▄▀█ ██▄ █▀▀ █▀▄ █▀▀ █▀▀ █▀▀ ▀█▀ ░░█ █░█ █░░ █▄░▄█ █▄░█ █▀█ █▀█ ▄▀▄ █▀█ ▄▀▀ ▀█▀
 █▀█ █▄█ █▄▄ █▄▀ ██▄ █▀░ █▄█ ▄█▄ █▄█ █▀▄ █▄▄ █░▀░█ █░▀█ █▄█ █▀▀ ▀▄█ █▀▄ ▄██ ░█░
ABCDEFGHIJKLMNOPQRST

 █░█ █░█ █░▄░█ ▀▄▀ █▄█ ▀█▀
 █▄█ ▀▄▀ █▀░▀█ █░█ ░█░ █▄▄
UVWXYZ
```

> Numbers:
```
 █▀█ ▄█ ▀█ ▀██ █░█ █▀ █▀ ▀▀█ █▄█ ██
 █▄█ ░█ █▄ ▄▄█ ▀▀█ ▄█ ██ ░░█ █▄█ ▄█
0123456789
```

> Punctuation: 
```
 ▄█▄█▀ ▄█▀ ▀░▄▀ ▄▀ ▀▄ █▀ ▀█ ░█▀ ▀█░ █░█ ▀ ░ ░ ░▄ ▄░ ░▀ ▀ ░░▄▀ ▀▄░░ █ ▀▄ ░░░ ▀▀
 ▄█▀█▀ ▄█▀ ▄▀░▄ ▀▄ ▄▀ █▄ ▄█ ▀█▄ ▄█▀ ░░░ ░ █ ▄ ▀▄ ▄▀ ▄█ ▄ ▄▀░░ ░░▀▄ ▄ ▄▀ ▄▄▄ ▀▀
#$%()[]{}´"',.<>;:/\!)_=
                                                                              
 ▀█ ▄▄ ▄█▄ ▀▄▀ ▄▀▄ ██ ░▄░▄
 ░▄ ░░ ░▀░ ▀░▀ ░░░ ██ ▀░▀░
?-+*^|~
```

> That character `ß`:
```
 ██▄
 █▄▀
ß
```

## Features:
- Lowercase and Uppercase differentiation
- ALL punctuation signs `#$%()[]{}´"',.<>;:/\!)_=?-+*^|~`, except `@` and `&`
- It has numbers `3` and `8` (_`8` is kinda weird.._), which were lacking on _the second font_
- It has the character `ß`

### CODE REVIEW

**Comment by pwaller** [comment]
Thanks for contributing this! If you want it to be available in the default install of pyfiglet, it needs to go in fonts-standard.

**Comment by peterbrittain** [comment]
Given the origins of this font and lack of clear license from that website, I suggest this is the right folder @pwaller

**Comment by pwaller** [comment]
I understood the provenance was from the PR contributor, so they could choose. If I am mistaken, then it is fine where it is. @CatPieLeaf any thoughts?

**Comment by peterbrittain** [comment]
Sorry, but we need to be careful...  The Fedora legal team would say that this needs to be @CatPieLeaf 's own work and have a clear license (e.g. the license for this project) before they would allow it in the default fonts downstream.  We need to make that clear in this PR (e.g. a statement from @CatPieLeaf to this effect) before moving.

**Comment by CatPieLeaf** [comment]
Well, this is the main reason i didn't try to submit the font to be added into the default fonts.

Since the font used others as pieces to be made plus some original work, and these others don't explicitly show their licenses, i have no idea if i am able to license it.
I'm new on this, and i don't know much about licensing.

**Comment by peterbrittain** [comment]
If you've sourced parts from another font, this is the right folder.

**Pull request merged**
