### PR TITLE
Port to importlib.resources

### PR DESCRIPTION
**Pull request by stefanor**
Port from `pkg_resources` to `importlib.resources`

(Closes: #113)

### CODE REVIEW

**Comment by stefanor** [comment]
Do we really still need to carry 2.7 support?

**Comment by pwaller** [comment]
Thanks for this! I'm not averse to dropping 2.7 in principle. It's nice to have but if the effort to keep it is too great, then we should drop it. If someone needs it they are welcome to contribute support.

Would you be able to drop it from the CI so we can get tests passing? I'm happy to cut a release quickly for this.

**Comment by pwaller** [comment]
Speedy :rocket:

**Comment by stefanor** [comment]
OK, the tests are now failing because we have fonts that don't parse.

I *think* this was a pre-existing issue, but wasn't noticed because `getFonts` was returning an empty list (fixed in the first commit here)

**Comment by stefanor** [comment]
I'm running out of time to look at this right now.

**Comment by pwaller** [comment]
Thank you for taking some time to look. I'll be away for the next week or so.

**Comment by stefanor** [comment]
I'll rebase out the commit that's triggering the bug (9b77825), and we can deal with that separately.

**Comment by stefanor** [comment]
Yeah, CI passes now.

**Comment by pwaller** [comment]
Thanks so much for taking the time to get to the bottom of this :1st_place_medal:. Changes look good to me.

**Pull request merged**
