### PR TITLE
Change LICENSE to MIT

### LINKED ISSUE #58: Alternatives to GPL-2.0 license?
First off, I just wanted to say that I love that you've spent the time to port FIGlet to Python.  This is a great project and I want to say thank you for creating it.  But that's not why I've raised this issue...  :-)  

It turns out that many of your dependent projects/packages (https://github.com/pwaller/pyfiglet/network/dependents) are using pyfiglet, but are not redistributing under the terms of the GPL-2.0 license that you are using.  My own package (https://github.com/peterbrittain/asciimatics) appears to have fallen foul of this.

I really want to continue to deploy my package under the terms of the Apache-2.0 license, which as I understand it means I have to follow one of the following options:

1. Remove/replace the use of your package
2. Convert all direct use of pyfiglet (via import) into separate process calls (via your command-line script).
3. Agree with you (as the copyright holders) a separate license for my project.
4. Persuade you to change your standard license to something that allows for this use case - e.g. LGPL-3.0.

Given how many other projects depend on this one (and are actually breaking the terms as I now understand them), I'd like to try to do the right thing here and explore options 3 and 4 with you before just diving into options 1 or 2.

So...  Would you be willing to consider some other form of licensing like LGPL?

### PR DESCRIPTION
**Pull request by pwaller**
Resolves #58.

### CODE REVIEW

**Comment by peterbrittain** [comment]
Was offline earlier...  Thanks for doing this.  

I saw the license mentioned in the README when I was editing it and a quick grep shows that there's also stuff in setup.py and pyfiglet/__init__.py.  I think these should all be updated or deleted.

**Comment by pwaller** [comment]
@peterbrittain thanks for catching that. Please take another look.

**Comment by peterbrittain** [comment]
Looks good to me!

**Comment by pwaller** [comment]
Thanks for your efforts on this @peterbrittain! :tada: :100:

**Comment by peterbrittain** [comment]
You're very welcome!  And thank you for being open to such a change.

**Pull request merged**
